# DCN模型配置
DCN:
  model_name: "DCN"
  model_save_dir: "/ModelZoo/DCN/DCN_torch/checkpoints/"  # 模型保存路径
  batch_size: 256                 # 批量大小
  epoch: 1                        # 训练轮次
  loss: "bce"                     # 损失函数
  optimizer: "adam"               # 优化器
  learning_rate: 0.001            # 学习率
  num_cross_layers: 3             # Cross层层数
  hidden_layers: [128, 64, 32]    # Deep层隐藏层维度
  dropout_p: 0.0                  # Dropout比率